{{- if .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "forgejo-runner-k8s.secretName" . }}
  labels:
    {{- include "forgejo-runner-k8s.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "forgejo-runner-k8s.secretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        token: "{{ `{{ .registrationToken }}` }}"
        registrationToken: "{{ `{{ .registrationToken }}` }}"
        apiToken: "{{ `{{ .apiToken }}` }}"
  data:
    - secretKey: registrationToken
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.registrationTokenRemoteKey | default .Values.secrets.externalSecrets.remoteKey }}
    - secretKey: apiToken
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.apiTokenRemoteKey | default .Values.secrets.externalSecrets.remoteKey }}
{{- end }}
